package geodata

import (
	"fmt"
	"os"
)

// GenerateMaxmindConfUsecase usecase
type GenerateMaxmindConfUsecase struct {
}

// NewGenerateMaxmindConfUsecase creates a new instance of InstallMaxMindLibraryUsecase
func NewGenerateMaxmindConfUsecase() *GenerateMaxmindConfUsecase {
	return &GenerateMaxmindConfUsecase{}
}

// Generate MaxMind Conf File
func (u *GenerateMaxmindConfUsecase) Generate(confPath string, accountID string, licenseKey string) error {
	confFile, err := os.Create(confPath)

	if err != nil {
		return err
	}

	defer confFile.Close()

	confFile.WriteString("# This MaxMind config file was generated by Tango \n")
	confFile.WriteString(fmt.Sprintf("AccountID %s\n", accountID))
	confFile.WriteString(fmt.Sprintf("LicenseKey %s\n", licenseKey))
	confFile.WriteString(fmt.Sprintf("EditionIDs %s\n", u.GetEditionIDs()))

	confFile.Sync()

	return nil
}

func (u *GenerateMaxmindConfUsecase) GetEditionIDs() string {
	return "GeoLite2-City"
}
