# .travis.yml
language: go

go:
  - 1.12.x

os:
  - linux
  - osx
  - windows

# Only clone the most recent commit.
git:
  depth: 1

env:
  global:
    # needed for the snap pipe:
    - PATH=/snap/bin:$PATH
    - GO111MODULE=on

# needed for the docker pipe
services:
  - docker

before_script:
  - go get -t -v ./...

script:
  - go build
  - go test

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true

notifications:
  email: false