# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Tango < Formula
  desc "Tango is a command-line tool for dancing with access logs"
  homepage "https://github.com/roma-glushko/tango"
  version "0.0.0-rc6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/roma-glushko/tango/releases/download/0.0.0-rc6/tango_0.0.0-rc6_macOS_64-bit.zip", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fbf89de981cd8f0f93d8dd687bb890f60ab1aecc292a589bdc0cc42a39516e8a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/roma-glushko/tango/releases/download/0.0.0-rc6/tango_0.0.0-rc6_Linux_64-bit.zip", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fd3064d71667a49383249d8663a5f1bbe0e2189e414c3fbaae8d7e4768f3375b"
    end
  end
  
  head "https://github.com/roma-glushko/tango.git"

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/program --version"
  end
end
