package geodata

import (
	"fmt"
	"os"
)

// GenerateMaxmindConfService services
type GenerateMaxmindConfService struct {
}

// NewGenerateMaxmindConfService creates a new instance of InstallMaxMindLibraryService
func NewGenerateMaxmindConfService() *GenerateMaxmindConfService {
	return &GenerateMaxmindConfService{}
}

// Generate MaxMind Conf File
func (u *GenerateMaxmindConfService) Generate(confPath string, accountID string, licenseKey string) error {
	confFile, err := os.Create(confPath)

	if err != nil {
		return err
	}

	defer func() { _ = confFile.Close() }()

	for _, line := range []string{
		"# This MaxMind config file was generated by Tango \n",
		fmt.Sprintf("AccountID %s\n", accountID),
		fmt.Sprintf("LicenseKey %s\n", licenseKey),
		fmt.Sprintf("EditionIDs %s\n", u.GetEditionIDs()),
	} {
		if _, err := confFile.WriteString(line); err != nil {
			return fmt.Errorf("failed to write config: %w", err)
		}
	}

	if err := confFile.Sync(); err != nil {
		return fmt.Errorf("failed to sync config file: %w", err)
	}

	return nil
}

// GetEditionIDs retrieves MaxMind Product IDs which are used by Tango
func (u *GenerateMaxmindConfService) GetEditionIDs() string {
	return "GeoLite2-City"
}
