# This file was generated by GoReleaser. DO NOT EDIT.
class Tango < Formula
  desc "Tango is a command-line tool for dancing with access logs"
  homepage "https://github.com/roma-glushko/tango"
  version "0.0.0-rc9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/roma-glushko/tango/releases/download/0.0.0-rc9/tango_0.0.0-rc9_macOS_64-bit.zip"
    sha256 "3779c29fe3506a9bed666c9d52978b98a3bdea2068f43697e5196ffb618406ab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/roma-glushko/tango/releases/download/0.0.0-rc9/tango_0.0.0-rc9_Linux_64-bit.zip"
      sha256 "85093c182c977213afea89f43a0f1aef3a6b081a5852170fc65f0e8f0a0a1579"
    end
  end
  
  head "https://github.com/roma-glushko/tango.git"

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/program --version"
  end
end
